### ISSUE TITLE
Object Error when clicking 'advanced tools (Kudu)'

### ISSUE THREAD

**Issue by DavidInsight** [Azure/Azure-AppServices-Diagnostics-Portal#310]
Hey there, 

I do not know if this issue should be here but since the website portal.azure is made (I believe) with TypeScripts I found most suitable to report it here.

**The error**
`[object Error]: {description: "Unable to get property 'name' of undefined or null reference", message: "Unable to get property 'name' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'name' of undefined or null reference at e.prototype.click (https://functions.azure.com/ng-min/7.25995cd868878958f62f.chunk.js:1:46076) at n.prototype.click (https://functions.azure.com/ng-min/7.25995cd868878958f62f.chunk.js:1:210277) at Anonymous function (https://functions.azure.com/ng-min/7.25995cd868878958f62f.chunk.js:1:214837) at handleEvent (https://functions.azure.com/ng-min/main.37bd9030b7f263ebaea7.bundle.js:1:472140) at handleEvent (https://functions.azure.com/ng-min/main.37bd9030b7f263ebaea7.bundle.js:1:483427) at Jr (https://functions.azure.com/ng-min/main.37bd9030b7f263ebaea7.bundle.js:1:443383) at Anonymous function (https://functions.azure.com/ng-min/main.37bd9030b7f263ebaea7.bundle.js:1:449208) at Anonymous function (https://functions.azure.com/ng-min/main.37bd9030b7f263ebaea7.bundle.js:1:252851) at t.prototype.invokeTask (https://functions.azure.com/ng-min/polyfills.9ffe93d727a9092970c9.bundle.js:1:48965) at onInvokeTask (https://functions.azure.com/ng-min/main.37bd9030b7f263ebaea7.bundle.js:1:410771)"}`

**The issue**
When I click the option 'advanced tools (kudu)' the page does not do anything and returns an error in the console

**What should happen**
I get inside the kudu settings like described in this article: 
https://get-vm.com/blog/2018/04/11/python-modules-azure-functions/

**Where**
resource-groups > your_resource > your_function_app > platform_features > advanced tools (kudu)

**When**
Has happened since today -> 17/04/2019 15:32:00 CEST 

(Edit) ***What I am using**
Internet Explorer Edge
Windows 10 Pro

Any solutions to enter that page without clicking there? (duh)

Again, if I have to post this elsewhere please let me know.

Thanks and laters!

**Comment by ShekharGupta1988** [comment]
fixed
