### ISSUE TITLE
Detector menu doesn't change when switch tabs

### ISSUE THREAD

**Issue by Sneezry** [Azure/Azure-AppServices-Diagnostics-Portal#833]
![1](https://user-images.githubusercontent.com/1621293/87268873-29c90a80-c4fe-11ea-9389-77bb05a0ec35.gif)

**Comment by Sneezry** [comment]
Any update on this issue? 😊

**Comment by ShekharGupta1988** [comment]
This issue has been fixed. Closing the issue.
