### ISSUE TITLE
Duplicate detector menu when swap category fast

### ISSUE THREAD

**Issue by Sneezry** [Azure/Azure-AppServices-Diagnostics-Portal#965]
![382bd2c2-2398-48d1-98fd-30e6015d5062](https://user-images.githubusercontent.com/1621293/98340089-c1231200-2047-11eb-98dd-9c3260ebc682.gif)

**Comment by ShekharGupta1988** [comment]
@Sneezry - Let me start a thread with you on this. I think we have released a new version of the portal and you should leverage that.

**Comment by ShekharGupta1988** [comment]
Moved to the newer version of portal.
